# Generated by Django 4.0.1 on 2022-01-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'visitor'},
        ),
    ]
